apiVersion: v1
kind: pod 
metadata:
  name: labels
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    